### ISSUE TITLE
How to add custom headers.

### ISSUE THREAD

**Issue by Kazunari001** [Avanade/CoreEx#128]
Hi team!
I am considering sending requests to external API.
The external APIs require specific headers to be added.
I am thinking of using `CoreEx.Http`, but I couldn't find a way to add custom headers.
Is there a way to add custom HTTP request headers in `CoreEx.Http` in `v3.27.2`?

Thanks.

**Comment by chullybun** [comment]
Hi @Kazunari001,

Here are a couple of ways to achieve, either using `CoreEx` or out-of-the-box .NET - it really depends on complexity, reusability, etc. as to which is the more appropriate.

Cheers...

--

### 1 - `TypedHttpClientBase`
Let's use the [`OktaHttpClient`](https://github.com/Avanade/Beef/blob/master/samples/MyEf.Hr/MyEf.Hr.Security.Subscriptions/OktaHttpClient.cs) in `MyEf.Hr` as an example. You can override `OnBeforeRequest` as follows - you have full access to the `HttpRequestMessage` before it is sent:

``` csharp
    protected override Task OnBeforeRequest(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Headers.Add("Fruit", "Apple");
        return Task.CompletedTask;
    }
```

### 2 - `DelegatingHandler`
The standard .NET [DelegatingHandler](https://learn.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers#custom-message-handlers) is the out-of-the-box means to handle. The `TypedHttpClientBase` support this, with the handlers being registered using the `AddTypedHttpClient` and corresponding `AddHttpMessageHandler`.

An example of a complex handler is here in the OData [readme](https://github.com/Avanade/CoreEx/tree/main/src/CoreEx.OData#authentication).

**Comment by Kazunari001** [comment]
Hi @chullybun ,
Thank you for suggestion a solution.
In this case, pattern 1 `TypedHttpClientBase` was suitable.
Thanks to that I was able to solve tha problem.
