### ISSUE TITLE
Refactoring questions - AddDatabase

### ISSUE THREAD

**Issue by karpikpl** [Avanade/CoreEx#38]
Do we need this extension method `builder.Services.AddDatabase(sp => new HrDb(sp.GetRequiredService<HrSettings>()));` ?
looks like `builder.Services.AddScoped<IDatabase, HrDb>();` would do the same?

**Comment by chullybun** [comment]
Good pickup. `AddDatabase` was provided to encapsulate in case other functionality needed to be added in the future when registering; added new `AddDatabase<TDb>()` overload to simplify. Also, now for Entity Framework, there is a new `AddEfDb<Tx, Ty>()` to similarly allow for future functionality when registering.
