### ISSUE TITLE
dotnet publish not working if check for IsDryRun enabled

### ISSUE THREAD

**Issue by AdiThakker** [Avanade/CoreEx#42]
@karpikpl : While playing with My.Hr.Infra project, I was not able to deploy the Web & Sql artifacts. When debugging, i came across  this line in [Apps.cs](https://github.com/Avanade/CoreEx/blob/main/samples/My.Hr/My.Hr.Infra/Components/Apps.cs) which prevents dotnet publish when doing a preview (i believe). Is this intended? 
![image](https://user-images.githubusercontent.com/19495619/194917045-e1b028e0-ed4b-48f4-a519-e37708063483.png)

Once I removed the above check, then I was able to publish the artifacts.

Let me know if this is correct understanding.

Thanks,
Adi.

**Comment by karpikpl** [comment]
yes, it's intended, but you need to check the latest code that's part of the template (on a branch), Infra project was deleted.

`IsDryRun` should be true only during "preview"

**Comment by karpikpl** [comment]
that method was slightly changed to handle dry run
[    private static async Task PublishApp()
    {
        if (Deployment.Instance.IsDryRun)
        {
            Directory.CreateDirectory("../Company.AppName.Api/bin/Release/net6.0/publish");
            Directory.CreateDirectory("../Company.AppName.Functions/bin/Release/net6.0/publish");
            return;
        }


        Log.Info("Setting up deployments from zip for the app and function and executing [dotnet publish]");


        var sw = Stopwatch.StartNew();
        var publishProcess = Process.Start(new ProcessStartInfo
        {
            WorkingDirectory = "../",
            FileName = "dotnet",
            Arguments = "publish --nologo -c RELEASE",
            RedirectStandardOutput = true,
            RedirectStandardError = true
        });
        await publishProcess!.WaitForExitAsync();
        sw.Stop();
        Log.Info($"[dotnet publish] completed in {sw.Elapsed}");
    }](https://github.com/Avanade/CoreEx/blob/1b266d97e55eeb7322c5a43a6f1f67b30fa66800/tools/CoreEx.Template/content/Company.AppName.Infra/Components/Apps.cs#L243-L266)

**Comment by AdiThakker** [comment]
Sounds good...I'll go ahead and close this issue.

Thanks,
Adi.
