### ISSUE TITLE
Error: Principal not found in the directory when creating resources using the templated code.

### ISSUE THREAD

**Issue by AdiThakker** [Avanade/CoreEx#43]
Hi @karpikpl  I am getting this following error when trying to create the resources of the  template generated code. The error is the following:  
<img width="766" alt="error" src="https://user-images.githubusercontent.com/19495619/196176135-4e268bcc-cbdc-40d0-99d4-09a0ad772abb.png">

Looks like its coming from here in the [Storage.cs](https://github.com/Avanade/CoreEx/blob/feature/template/tools/CoreEx.Template/content/Company.AppName.Infra/Components/Storage.cs):
<img width="377" alt="image" src="https://user-images.githubusercontent.com/19495619/196176980-e0fea501-05b4-4e87-b73a-1bcba9c18a81.png"> 

Which is being called from here as PrincipalType as "Group" in 
[CompanyAppNameStack.cs](https://github.com/Avanade/CoreEx/blob/feature/template/tools/CoreEx.Template/content/Company.AppName.Infra/CompanyAppNameStack.cs):
<img width="288" alt="image" src="https://user-images.githubusercontent.com/19495619/196177577-9f75d05d-a3a0-4bb8-9810-3a7d003c6068.png">

It complains about Prinicipal does not exist in the directory. I'll contiunue to look into it but just thought i'll put it here if in case you have some thoughts?

Thanks,
Adi.

**Comment by AdiThakker** [comment]
One thing in noticed that this error is not consistent, if I debug through the code, then it succeeded....could it be related to the timing / race condition?

**Comment by karpikpl** [comment]
Access for dev-group is a feature that gives access to "developers".
It's enabled by specifying a configuration value - 'developerEmails'. That's covered in the readme file.

**Comment by karpikpl** [comment]
if this wasn't reproduced, can we close it?

**Comment by AdiThakker** [comment]
Yes.. This can be closed!

Adi.

Sent from Surface Duo
________________________________
