### ISSUE TITLE
Question, re: DatabaseExtendedExtensions.ReferenceData "*Fixed:* Potential SQL Injection" in v2.5.0

### ISSUE THREAD

**Issue by sean-bloch** [Avanade/CoreEx#54]
I see the update regarding SQL Injection mitigations includes a 
```csharp
new NotSupportedException("Database Provider can not CreateCommandBuilder which is required to quote the identifiers to minimize SQL inject possibility.")
``` 

Are there any instances of Database Providers that are now "not supported", that would have been prior?

**Comment by chullybun** [comment]
@sean-bloch, short answer is no. The only _currently_ supported database providers are SQL Server and MySQL - these both can create command builders. This is to handle any potential future database provider usage to output a meaningful exception where support is not included.
